config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/student'

  get 'dashboard/parent'

  get 'dashboard/teacher'

  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'

  resources :assignments
  resources :grades
  resources :parents
  resources :students
  resources :teachers

  get 'dashboard/index'
  root 'dashboard#index'

  get 'api/teachers' => 'teachers#index'
  get 'api/teachers/:id' => 'teachers#show'
  get 'api/students' => 'students#index'
  get 'api/students/:id' => 'students#show'
  get 'api/assignments' => 'assignments#index'
  get 'api/assignments' => 'assignments#show'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :assignment
  belongs_to :student
  
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :teacher_logged_in?
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
    @assignments = Assignment.all
  end

  # GET /grades/new
  def new
    @grade = Grade.new(student_id: params[:student_id])
    @assignments = Assignment.all
  end

  # GET /grades/1/edit
  def edit
    @assignments = Assignment.all
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)
    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:assignment_id, :score, :student_id, :upload_pdf)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="app-form">
    <div class="field">
      <%= f.label :assignment_id %><br>
      <%= f.select :assignment_id, @assignments.map{ |a| [a.name, a.id] } %>
    </div>
    <div class="field">
      <%= f.label :score %><br>
      <%= f.number_field :score %>
    </div>
    <div class="field">
      <%= f.hidden_field :student_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form' %>

<div >
  <%= link_to 'Show', @grade %>
  <%= link_to 'View All Grades', grades_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/grades/index.html.erb
<h1>Listing Grades</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Assignment</th>
      <th>Score</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.assignment.name %></td>
        <td><%= grade.score %></td>
        <td><%= grade.student.name %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div >
  <%= link_to 'New Grade', new_grade_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form' %>

<div >
  <%= link_to 'View All Grades', grades_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/grades/show.html.erb
<p>
  <strong>Assignment:</strong>
  <%= @grade.assignment.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @grade.score %>
</p>

<p>
  <strong>Student:</strong>
  <%= @grade.student.name %>
</p>

<div >
  <%= link_to 'Edit', edit_grade_path(@grade) %>
  <%= link_to 'View All Grades', grades_path %>
  <%= link_to 'Home', root_path %>
</div>