config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/student'

  get 'dashboard/parent'

  get 'dashboard/teacher'

  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'

  resources :assignments
  resources :grades
  resources :parents
  resources :students
  resources :teachers

  get 'dashboard/index'
  root 'dashboard#index'

  get 'api/teachers' => 'teachers#index'
  get 'api/teachers/:id' => 'teachers#show'
  get 'api/students' => 'students#index'
  get 'api/students/:id' => 'students#show'
  get 'api/assignments' => 'assignments#index'
  get 'api/assignments' => 'assignments#show'

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :grades
  has_many :parents
  belongs_to :teacher
  has_secure_password

  def get_grade(id)
    grades.find_by_assignment_id(id).score
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :teacher_logged_in?
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @teacher = Teacher.find_by_id(session[:user_id])
    @student = Student.new(teacher_id: session[:user_id])
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :password)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="app-form">


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.hidden_field :teacher_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  </div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<div >
  <%= link_to 'Show', @student %>
  <%= link_to 'View All Students', students_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/students/index.html.erb
<h1>Listing Students</h1>

<table class="tables">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="5"> Options </th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Add Parent', new_parent_path(student_id: student.id) %></td>
        <td><%= link_to 'Add Grade', new_grade_path(student_id: student.id) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div >
  <%= link_to 'New Student', new_student_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<div>
  <%= link_to 'View Roster', students_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/students/show.html.erb
<div class="app-form">


  <p>
    <strong>Name:</strong>
    <%= @student.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @student.email %>
  </p>

  <p>
    <strong>Grades:</strong>

  </p>



  <div >
    <%= link_to 'Edit', edit_student_path(@student) %>
    <%= link_to 'View Roster', students_path %>
    <%= link_to 'Home', root_path %>
  </div>
</div>