config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/student'

  get 'dashboard/parent'

  get 'dashboard/teacher'

  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'

  resources :assignments
  resources :grades
  resources :parents
  resources :students
  resources :teachers

  get 'dashboard/index'
  root 'dashboard#index'

  get 'api/teachers' => 'teachers#index'
  get 'api/teachers/:id' => 'teachers#show'
  get 'api/students' => 'students#index'
  get 'api/students/:id' => 'students#show'
  get 'api/assignments' => 'assignments#index'
  get 'api/assignments' => 'assignments#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gradebook</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"> <%= link_to "New Assignment", new_assignment_path, class: "navbar" %> </li>
        <li class="nav-link">   <%= link_to "All Assignments", assignments_path, class: "navbar" %> </li>
        <li class="nav-link"> <%= link_to "New Student", new_student_path, class: "navbar" %> </li>
        <li class="nav-link">   <%= link_to "View Students", students_path, class: "navbar" %> </li>
        <li class="nav-link">   <%= link_to "View Parents", parents_path, class: "navbar" %> </li>
        <a><%= link_to "Logout", sessions_logout_path if session[:user_id] %></a>

      </ul>

    </nav>

  </div>
</header>
<body>


  <p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>

  <!-- <div>
    <p class="audioplayer_container">
      <object type="application/x-shockwave-flash" name="audioplayer_1" style="outline: none" data="http://lauranova.com/wp-content/plugins/audio-player/assets/player.swf?ver=2.0.4.1" width="290" height="24" id="audioplayer_1">
        <param name="bgcolor" value="#FFFFFF">
        <param name="wmode" value="transparent">
        <param name="menu" value="true">
        <param name="flashvars" value="animation=yes&amp;encode=yes&amp;initialvolume=100&amp;remaining=no&amp;noinfo=no&amp;buffer=5&amp;checkpolicy=no&amp;rtl=no&amp;bg=f8f8f8&amp;text=666666&amp;leftbg=eeeeee&amp;lefticon=666666&amp;volslider=666666&amp;voltrack=FFFFFF&amp;rightbg=cccccc&amp;rightbghover=999999&amp;righticon=666666&amp;righticonhover=ffffff&amp;track=FFFFFF&amp;loader=9FFFB8&amp;border=666666&amp;tracker=DDDDDD&amp;skip=666666&amp;soundFile=aHR0cDovL2xhdXJhbm92YS5jb20vYXVkaW8vc3BlZWNobGVzcy5tcDM&amp;playerID=audioplayer_1">
      </object>
    </p>
  </div>

  <a href="javascript:void(0)" id="playsound">At Station</a>

  <audio id="sound_effect" class="audio_player" preload="auto">
    <source src="http://soundfxnow.com/soundfx/WritingOnChalkboard1.mp3" type="audio/mp3">
  </audio>
  <%= audio_tag(asset_url("chalk1.mp3"), autoplay: true, controls: true) %> -->

</body>

<!-- <div class="wrapper-for-content-outside-of-footer">
</div>

<footer class="footer-2" role="contentinfo">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
    <ul>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>

    <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Terms and Conditions</a></li>
        <li><a href="javascript:void(0)">Privacy Policy</a></li>
      </ul>

      <ul class="footer-social">
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
          </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
        </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
        </a></li>
      </ul>
    </div>
</footer> -->


</html>